# Generated by Django 6.0.7 on 2026-07-12 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('lost', 'lost'), ('found', 'found ')], default='lost')),
                ('status', models.CharField(choices=[('claimed', 'claimed'), ('open', 'open '), ('resolved', 'Found ')], default='open')),
                ('item_name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date_incident', models.DateField(help_text='Date the item was lost or found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
